___

<a href='http://www.pieriandata.com'> <img src='../Pierian_Data_Logo.png' /></a>
___

# NumPy

`numpy` es una biblioteca de álgebra lineal para Python. La razón por la que es tan importante para la ciencia de datos con Python es que casi todas las bibliotecas del ecosistema PyData se basan en `numpy` como uno de sus principales componentes básicos.

Numpy también es increíblemente rápido, ya que tiene enlaces a bibliotecas C. Para obtener más información sobre por qué es mejor utilizar matrices en lugar de listas, echa un vistazo a esta excelente [publicación de StackOverflow](http://stackoverflow.com/questions/993984/why-numpy-instead-of-python-lists).



## Instrucciones de instalación

Si vas a usar esta librería en local, se recomienda encarecidamente instalar Python utilizando la distribución Anaconda para asegurarse de que todas las dependencias subyacentes (como las bibliotecas de álgebra lineal) se sincronizan con el uso de una instalación conda. Si tiene Anaconda, instale NumPy yendo a su terminal o símbolo del sistema y escribiendo:
    
    conda install numpy
    


## Uso de `numpy`

Una vez instalado, ya podemos importarlo en nuestro código:

In [ ]:
import numpy as np

`numpy` tiene muchas funciones y capacidades integradas. No las cubriremos todas en este taller, sino que nos centraremos en algunos de sus aspectos más importantes: vectores, matrices y generación de números. Comencemos hablando de las matrices.

# Matrices `numpy`

Las matrices `numpy` son la forma principal en que utilizaremos `numpy` a lo largo del curso. Las matrices `numpy` se dividen básicamente en dos tipos: vectores y matrices. Los vectores son matrices estrictamente unidimensionales y las matrices son bidimensionales (pero hay que tener en cuenta que una matriz puede tener solo una fila o una columna).

## Creación de matrices `numpy`

### A partir de una lista Python

Podemos crear una matriz convirtiendo directamente una lista o una lista de listas:

In [ ]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [ ]:
np.array(my_list)

array([1, 2, 3])

In [ ]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Built-in Methods

There are lots of built-in ways to generate Arrays

### arange

Devuelve valores espaciados uniformemente dentro de un intervalo dado.

In [ ]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

### `zeros` y `ones`
Generar matrices de ceros o unos

In [ ]:
np.zeros(3)

array([ 0.,  0.,  0.])

In [ ]:
np.zeros((5,5))

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [ ]:
np.ones(3)

array([ 1.,  1.,  1.])

In [ ]:
np.ones((3,3))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

### linspace
Devuelve números espaciados uniformemente en un intervalo especificado.

In [ ]:
np.linspace(0,10,3)

array([  0.,   5.,  10.])

In [ ]:
np.linspace(0,10,50)

array([  0.        ,   0.20408163,   0.40816327,   0.6122449 ,
         0.81632653,   1.02040816,   1.2244898 ,   1.42857143,
         1.63265306,   1.83673469,   2.04081633,   2.24489796,
         2.44897959,   2.65306122,   2.85714286,   3.06122449,
         3.26530612,   3.46938776,   3.67346939,   3.87755102,
         4.08163265,   4.28571429,   4.48979592,   4.69387755,
         4.89795918,   5.10204082,   5.30612245,   5.51020408,
         5.71428571,   5.91836735,   6.12244898,   6.32653061,
         6.53061224,   6.73469388,   6.93877551,   7.14285714,
         7.34693878,   7.55102041,   7.75510204,   7.95918367,
         8.16326531,   8.36734694,   8.57142857,   8.7755102 ,
         8.97959184,   9.18367347,   9.3877551 ,   9.59183673,
         9.79591837,  10.        ])

## `eye`

Crea una matriz identidad.

In [ ]:
np.eye(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

## Generación aletatoria

`numpy` también ofrece muchas formas de crear matrices de números aleatorios:

### `rand`
Crea una matriz con la forma dada y la rellena con
muestras aleatorias de una distribución uniforme
entre ``[0, 1)``.

In [ ]:
np.random.rand(2)

array([ 0.11570539,  0.35279769])

In [ ]:
np.random.rand(5,5)

array([[ 0.66660768,  0.87589888,  0.12421056,  0.65074126,  0.60260888],
       [ 0.70027668,  0.85572434,  0.8464595 ,  0.2735416 ,  0.10955384],
       [ 0.0670566 ,  0.83267738,  0.9082729 ,  0.58249129,  0.12305748],
       [ 0.27948423,  0.66422017,  0.95639833,  0.34238788,  0.9578872 ],
       [ 0.72155386,  0.3035422 ,  0.85249683,  0.30414307,  0.79718816]])

### `randn`

Devuelve una muestra (o muestras) de la distribución *normal estándar*. A diferencia de rand, que es uniforme:

In [ ]:
np.random.randn(2)

array([-0.27954018,  0.90078368])

In [ ]:
np.random.randn(5,5)

array([[ 0.70154515,  0.22441999,  1.33563186,  0.82872577, -0.28247509],
       [ 0.64489788,  0.61815094, -0.81693168, -0.30102424, -0.29030574],
       [ 0.8695976 ,  0.413755  ,  2.20047208,  0.17955692, -0.82159344],
       [ 0.59264235,  1.29869894, -1.18870241,  0.11590888, -0.09181687],
       [-0.96924265, -1.62888685, -2.05787102, -0.29705576,  0.68915542]])

### `randint`
Devuelve números enteros aleatorios entre `low` (incluido) y `high` (excluido).

In [ ]:
np.random.randint(1,100)

44

In [ ]:
np.random.randint(1,100,10)

array([13, 64, 27, 63, 46, 68, 92, 10, 58, 24])

## Atributos y métodos de las matrices

Veamos algunos atributos y métodos útiles de las matrices:

In [ ]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [ ]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
ranarr

array([10, 12, 41, 17, 49,  2, 46,  3, 19, 39])

### `reshape`
Devuelve una matriz que contiene los mismos datos con una nueva forma.

In [ ]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### `max,min,argmax,argmin`

Estos son métodos útiles para encontrar valores máximos o mínimos. O para encontrar sus ubicaciones de índice utilizando argmin o argmax.

In [ ]:
ranarr

array([10, 12, 41, 17, 49,  2, 46,  3, 19, 39])

In [ ]:
ranarr.max()

49

In [ ]:
ranarr.argmax()

4

In [ ]:
ranarr.min()

2

In [ ]:
ranarr.argmin()

5

### `shape`

`shape` es un atributo que tienen las matrices (no un método):

In [ ]:
# Vector
arr.shape

(25,)

In [ ]:
# Notice the two sets of brackets
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24]])

In [ ]:
arr.reshape(1,25).shape

(1, 25)

In [ ]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [ ]:
arr.reshape(25,1).shape

(25, 1)

### `dtype`

También puede obtener el tipo de datos del objeto en la matriz:

In [ ]:
arr.dtype

dtype('int64')

# Indexación y selección

En esta clase veremos cómo seleccionar elementos o grupos de elementos de una matriz.

In [ ]:
#Vamos a crear un array muy simple
arr = np.arange(0,11)
arr

## Indexación y selección de corchetes
La forma más sencilla de seleccionar uno o varios elementos de una matriz es muy similar a las listas de Python:

In [ ]:
arr[8]

In [ ]:

arr[1:5]

## Difusión

Las matrices `numpy` se diferencian de una lista Python normal por su capacidad de difusión:

In [ ]:

arr[0:5]=100
arr


In [ ]:
arr = np.arange(0,11)
arr

In [ ]:
slice_of_arr = arr[0:6]
slice_of_arr

In [ ]:
slice_of_arr[:]=99
slice_of_arr

Ahora fíjate en que los cambios también se producen en nuestra matriz original.

In [ ]:
arr

Los datos no se copian, ¡es una vista de la matriz original! Esto evita problemas de memoria.

In [ ]:
#Para obtener una copia debemos usar el método copy
arr_copy = arr.copy()

arr_copy

## Indexación de una matriz 2D (matrices)

El formato general es **arr_2d[row][col]** o **arr_2d[row,col]**. Recomiendo utilizar normalmente la notación con comas para mayor claridad.

In [ ]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))
arr_2d

In [ ]:
#Obteniendo una fila
arr_2d[1]

In [ ]:
# El formato es arr_2d[fila][columna] o arr_2d[fila,columna]

# Obtener el valor de un elemento individual
arr_2d[1][0]

In [ ]:
# Obtener el valor de un elemento individual
arr_2d[1,0]

In [ ]:
# Segmentación de matriz 2D

#Forma (2,2) desde la esquina superior derecha
arr_2d[:2,1:]

In [ ]:
#Forma fila inferior
arr_2d[2]

## Fancy Indexing

Esta forma de indexacción nos permite seleccionar filas o columnas completas fuera de orden. Para mostrarlo, creemos rápidamente una matriz numpy:

In [ ]:
arr2d = np.zeros((10,10))
arr_length = arr2d.shape[1]

for i in range(arr_length):
    arr2d[i] = i

arr2d

Usando *fancy indexing* podemos hacer lo siguiente:

In [ ]:
arr2d[[2,4,6,8]]

In [ ]:
arr2d[[6,4,2,7]]

## Selección

Repasemos brevemente cómo utilizar los corchetes para la selección basada en operadores de comparación.

In [ ]:
arr = np.arange(1,11)
arr

In [ ]:
arr > 4

In [ ]:
bool_arr = arr>4
bool_arr

In [ ]:
arr[bool_arr]

In [ ]:
arr[arr>2]

In [ ]:
x = 2
arr[arr>x]

# Operaciones



## Aritméticas

Puedes realizar fácilmente operaciones aritméticas con matrices o con escalares. Veamos algunos ejemplos:

In [ ]:
arr = np.arange(0,10)
arr + arr

In [ ]:
arr * arr

In [ ]:
arr - arr

In [ ]:
# Obtenemos un warning sobre división por cero

arr/arr

In [ ]:
# También obtenemos un warning
1/arr

In [ ]:
arr**3

## Funciones universales de matrices

Numpy incluye muchas [funciones universales de matrices](http://docs.scipy.org/doc/numpy/reference/ufuncs.html), que son básicamente operaciones matemáticas que se pueden utilizar para realizar operaciones en toda la matriz. Veamos algunas de las más comunes:

In [ ]:
# Raíz cuadrada
np.sqrt(arr)

In [ ]:
#Cálculo exponencial (e^)
np.exp(arr)

In [ ]:
np.max(arr) #igual que arr.max()

In [ ]:
np.sin(arr)

# Ejercicios

Vamos ahora a dedicar algo de tiempo a intentar realizar una serie de ejercicios para asentar todo lo que hemos visto de la librearía `numpy`

#### Importa NumPy como np


#### Crea un array de 10 unos


#### Crea un array de 10 cincos


#### Crea un array con los enteros del 10 al 50


#### Crea un array con todos los números pares del 10 al 50


#### Crea una matriz 3x3 con valores del 0 al 8


#### Crea una matriz identidad 3x3


#### Usa NumPy para generar un número aleatorio entre 0 y 1


#### Usa `numpy` para generar un array de 25 números aleatorios sacados de una distribución normal estándar


#### Crea un array de 20 puntos espaciados linealmente entre 0 y 1


## Indexación y selección en NumPy

Ahora se te darán algunas matrices y tendrás que replicar los resultados que se muestran:


In [ ]:
mat = np.arange(1,26).reshape(5,5)
mat

### Ahora haz lo siguiente


In [ ]:
#ESCRIBE AQUÍ EL CÓDIGO QUE REPRODUCE EL RESULTADO DE LA CELDA DE ABAJO.


array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [ ]:
#ESCRIBE AQUÍ EL CÓDIGO QUE REPRODUCE EL RESULTADO DE LA CELDA DE ABAJO.


20

In [ ]:
#ESCRIBE AQUÍ EL CÓDIGO QUE REPRODUCE EL RESULTADO DE LA CELDA DE ABAJO.


array([[ 2],
       [ 7],
       [12]])

In [ ]:
#ESCRIBE AQUÍ EL CÓDIGO QUE REPRODUCE EL RESULTADO DE LA CELDA DE ABAJO.


array([21, 22, 23, 24, 25])


In [ ]:
#ESCRIBE AQUÍ EL CÓDIGO QUE REPRODUCE EL RESULTADO DE LA CELDA DE ABAJO.


array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

#### Saca la suma de todos los valores en `mat`


#### Calcula la desviación estándar de los valores en `mat`


#### Saca la suma de todas las columnas en `mat`


¡Eso es todo amigos!