# Introduccion a la librería NumPy

`numpy` es una biblioteca de álgebra lineal para Python. La razón por la que es tan importante para la ciencia de datos con Python es que casi todas las bibliotecas del ecosistema PyData se basan en `numpy` como uno de sus principales componentes básicos.

Numpy también es increíblemente rápido, ya que tiene enlaces a bibliotecas C. Para obtener más información sobre por qué es mejor utilizar matrices en lugar de listas, echa un vistazo a esta excelente [publicación de StackOverflow](http://stackoverflow.com/questions/993984/why-numpy-instead-of-python-lists).



## Instrucciones de instalación

Si vas a usar esta librería en local, se recomienda encarecidamente instalar Python utilizando la distribución Anaconda para asegurarse de que todas las dependencias subyacentes (como las bibliotecas de álgebra lineal) se sincronizan con el uso de una instalación conda.
    
    conda install numpy
    


## Uso de `numpy`

Una vez instalado, ya podemos importarlo en nuestro código:

In [ ]:
import numpy as np

`numpy` tiene muchas funciones y capacidades integradas. No las cubriremos todas en este taller, sino que nos centraremos en algunos de sus aspectos más importantes: vectores, matrices y generación de números. Comencemos hablando de las matrices.

# Matrices `numpy`

Las matrices `numpy` son la forma principal en que utilizaremos `numpy` a lo largo del taller. Las matrices `numpy` se dividen básicamente en dos tipos: vectores y matrices.

- Los vectores son matrices estrictamente unidimensionales y
- las matrices son bidimensionales (pero hay que tener en cuenta que una matriz puede tener solo una fila o una columna).

## Creación de matrices `numpy`

### A partir de una lista Python

Podemos crear una matriz convirtiendo directamente una lista o una lista de listas:

In [ ]:
my_list = [1,2,3]
my_list

In [ ]:
np.array(my_list)

In [ ]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

In [ ]:
np.array(my_matrix)

## Built-in Methods

`numpy` contiene una gran cantidad de métodos propios para generar listas con un determinado contenido.

### arange

Devuelve valores espaciados uniformemente dentro de un intervalo dado.

In [ ]:
np.arange(0,10)

In [ ]:
np.arange(0,11,2)

### `zeros` y `ones`
Generar matrices de ceros o unos

In [ ]:
np.zeros(3)

In [ ]:
np.zeros((5,5))

In [ ]:
np.ones(3)

In [ ]:
np.ones((3,3))

### `linspace`
Devuelve números espaciados uniformemente en un intervalo especificado.

In [ ]:
np.linspace(0,10,3)

In [ ]:
np.linspace(0,10,50)

### `eye`

Crea una matriz identidad.

In [ ]:
np.eye(4)

## Generación aletatoria

`numpy` también ofrece muchas formas de crear matrices de números aleatorios:

### `rand`
Crea una matriz con la forma dada y la rellena con
muestras aleatorias de una distribución uniforme
entre ``[0, 1)``.

In [ ]:
np.random.rand(2)

In [ ]:
np.random.rand(5,5)

### `randn`

Devuelve una muestra (o muestras) de la distribución *normal estándar*. A diferencia de rand, que es uniforme:

In [ ]:
np.random.randn(2)

In [ ]:
np.random.randn(5,5)

### `randint`
Devuelve números enteros aleatorios entre `low` (incluido) y `high` (excluido).

In [ ]:
np.random.randint(1,100)

In [ ]:
np.random.randint(1,100,10)

## Atributos y métodos de las matrices

Veamos algunos atributos y métodos útiles de las matrices:

In [ ]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [ ]:
arr

In [ ]:
ranarr

### `max,min,argmax,argmin`

Estos son métodos útiles para encontrar valores máximos o mínimos. O para encontrar sus ubicaciones de índice utilizando argmin o argmax.

In [ ]:
ranarr

In [ ]:
ranarr.max()

In [ ]:
ranarr.argmax()

In [ ]:
ranarr.min()

In [ ]:
ranarr.argmin()

### `shape` y `reshape`

`shape` es un atributo que tienen las matrices (no un método) y `reshape` devuelve una matriz que contiene los mismos datos con una nueva forma.

In [ ]:
# Vector
arr.shape

In [ ]:
# Notice the two sets of brackets
arr.reshape(1,25)

In [ ]:
arr.reshape(1,25).shape

In [ ]:
arr.reshape(25,1)

In [ ]:
arr.reshape(25,1).shape

### `dtype`

También puede obtener el tipo de datos del objeto en la matriz:

In [ ]:
arr.dtype

# Indexación y selección

En esta clase veremos cómo seleccionar elementos o grupos de elementos de una matriz.

In [ ]:
#Vamos a crear un array muy simple
arr = np.arange(0,11)
arr

## Indexación y selección de corchetes
La forma más sencilla de seleccionar uno o varios elementos de una matriz es muy similar a las listas de Python:

In [ ]:
arr[8]

In [ ]:

arr[1:5]

## Difusión

Las matrices `numpy` se diferencian de una lista Python normal por su capacidad de difusión:

In [ ]:
arr[0:5]=100
arr

In [ ]:
arr = np.arange(0,11)
arr

In [ ]:
slice_of_arr = arr[0:6]
slice_of_arr

In [ ]:
slice_of_arr[:]=99
slice_of_arr

Ahora fíjate en que los cambios también se producen en nuestra matriz original.

In [ ]:
arr

Los datos no se copian, ¡es una vista de la matriz original! Esto evita problemas de memoria.

In [ ]:
#Para obtener una copia debemos usar el método copy
arr_copy = arr.copy()

arr_copy

## Indexación de una matriz 2D

El formato general es `arr_2d[row][col]` o `arr_2d[row,col]`. Recomiendo utilizar normalmente la notación con comas para mayor claridad.

In [ ]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))
arr_2d

In [ ]:
#Obteniendo una fila
arr_2d[1]

In [ ]:
# El formato es arr_2d[fila][columna] o arr_2d[fila,columna]

# Obtener el valor de un elemento individual
arr_2d[1][0]

In [ ]:
# Obtener el valor de un elemento individual
arr_2d[1,0]

In [ ]:
# Segmentación de matriz 2D

#Forma (2,2) desde la esquina superior derecha
arr_2d[:2,1:]

In [ ]:
#Forma fila inferior
arr_2d[2]

## Fancy Indexing

Esta forma de indexacción nos permite seleccionar filas o columnas completas fuera de orden. Para mostrarlo, creemos rápidamente una matriz numpy:

In [ ]:
arr2d = np.zeros((10,10))
arr_length = arr2d.shape[1]

for i in range(arr_length):
    arr2d[i] = i

arr2d

Usando *fancy indexing* podemos hacer lo siguiente:

In [ ]:
arr2d[[2,4,6,8]]

In [ ]:
arr2d[[6,4,2,7]]

## Selección

Repasemos brevemente cómo utilizar los corchetes para la selección basada en operadores de comparación.

In [ ]:
arr = np.arange(1,11)
arr

In [ ]:
arr > 4

In [ ]:
bool_arr = arr>4
bool_arr

In [ ]:
arr[bool_arr]

In [ ]:
arr[arr>2]

In [ ]:
x = 2
arr[arr>x]

# Operaciones



## Aritméticas

Puedes realizar fácilmente operaciones aritméticas con matrices o con escalares. Veamos algunos ejemplos:

In [ ]:
arr = np.arange(0,10)
arr + arr

In [ ]:
arr * arr

In [ ]:
arr - arr

In [ ]:
# Obtenemos un warning sobre división por cero

arr/arr

In [ ]:
# También obtenemos un warning
1/arr

In [ ]:
arr**3

## Funciones universales de matrices

Numpy incluye muchas [funciones universales de matrices](http://docs.scipy.org/doc/numpy/reference/ufuncs.html), que son básicamente operaciones matemáticas que se pueden utilizar para realizar operaciones en toda la matriz. Veamos algunas de las más comunes:

In [ ]:
# Raíz cuadrada
np.sqrt(arr)

In [ ]:
#Cálculo exponencial (e^)
np.exp(arr)

In [ ]:
np.max(arr) #igual que arr.max()

In [ ]:
np.sin(arr)

# Ejercicios

Vamos ahora a dedicar algo de tiempo a intentar realizar una serie de ejercicios para asentar todo lo que hemos visto de la librearía `numpy`

Importa NumPy como np


Crea un array de 10 unos


Crea un array de 10 cincos


Crea un array con los enteros del 10 al 50


Crea un array con todos los números pares del 10 al 50


Crea una matriz 3x3 con valores del 0 al 8


Crea una matriz identidad 3x3


Usa NumPy para generar un número aleatorio entre 0 y 1


Usa `numpy` para generar un array de 25 números aleatorios sacados de una distribución normal estándar


Crea un array de 20 puntos espaciados linealmente entre 0 y 1


## Indexación y selección en NumPy

Ahora se te darán algunas matrices y tendrás que replicar los resultados que se muestran:


In [ ]:
mat = np.arange(1,26).reshape(5,5)
mat

Ahora haz lo siguiente


In [ ]:
#ESCRIBE AQUÍ EL CÓDIGO QUE REPRODUCE EL RESULTADO DE LA CELDA DE ABAJO.


array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [ ]:
#ESCRIBE AQUÍ EL CÓDIGO QUE REPRODUCE EL RESULTADO DE LA CELDA DE ABAJO.


20

In [ ]:
#ESCRIBE AQUÍ EL CÓDIGO QUE REPRODUCE EL RESULTADO DE LA CELDA DE ABAJO.


array([[ 2],
       [ 7],
       [12]])

In [ ]:
#ESCRIBE AQUÍ EL CÓDIGO QUE REPRODUCE EL RESULTADO DE LA CELDA DE ABAJO.


array([21, 22, 23, 24, 25])


In [ ]:
#ESCRIBE AQUÍ EL CÓDIGO QUE REPRODUCE EL RESULTADO DE LA CELDA DE ABAJO.


array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

Saca la suma de todos los valores en `mat`


Calcula la desviación estándar de los valores en `mat`


Saca la suma de todas las columnas en `mat`


¡Eso es todo amigos!